### ISSUE TITLE
HTTPError: HTTP 403: User 'root' is not authorized to start kernel 'Spark - Python (YARN Cluster Mode)'. Ensure KERNEL_USERNAME is set to an appropriate value and retry the request.

### ISSUE THREAD

**Issue by ridwanoabdulazeez** [jupyter-incubator/enterprise_gateway#438]
[E 20:03:27.282 NotebookApp] Uncaught exception POST /api/sessions (10.93.129.49)
    HTTPServerRequest(protocol='http', host='ulviasp06097.fg.rbc.com:8889', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='10.93.129.49')
    Traceback (most recent call last):
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
        type=mtype))
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/nb2kg/managers.py", line 333, in create_session
        session_id, path, name, type, kernel_name,
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/nb2kg/managers.py", line 145, in start_kernel
        response = yield fetch_kg(self.kernels_endpoint, method='POST', body=json_body)
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/app/anaconda2/lib/python2.7/site-packages/nb2kg/managers.py", line 64, in fetch_kg
        response = yield client.fetch(url, **kwargs)
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/app/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    HTTPError: HTTP 403: User 'root' is not authorized to start kernel 'Spark - Python (YARN Cluster Mode)'. Ensure KERNEL_USERNAME is set to an appropriate value and retry the request.

I am getting the above error. Any help will be appreciated

**Comment by kevin-bates** [comment]
@ridwanoabdulazeez - thanks for checking out Enterprise Gateway.

By default, `root` is an [unauthorized user](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-security.html#authorization).  This can be "undone" by setting your own set of unauthorized users or you can set `KERNEL_USERNAME` from your client to a value that is not root. 

The fact that `root` is being encountered here in implies that `KERNEL_USERNAME` is not being sent the kernel creation request **and** that your EG is running as root.  We would recommend running EG as a non-root user and passing a value for `KERNEL_USERNAME`.  Please note that NB2KG will automatically _flow_ any environment variables prefixed with `KERNEL_` or any in the `KG_ENV_WHITELIST` value.

**Comment by ridwanoabdulazeez** [comment]
Thanks @kevin-bates 
Will this modifications be done in the run.sh script?

**Comment by ridwanoabdulazeez** [comment]
Thanks @kevin-bates . The problem has been fixed

**Comment by Litchilitchy** [comment]
@kevin-bates FYI, we found one thing might be issue

As you said, use dummy to set `unauthorized_users` could work. But as the error raising, or the one used in `jupyter_enterprise_gateway_config.py`, it leads us to set it as `...unauthorized_users={}`

However this would still encounter error, the one works should be `...unauthorized_users=[]` (we guessed many times to get this one work, we think it is hard to infer from your error msg)

**Comment by kevin-bates** [comment]
I'm not sure what the issue is here. Does using `...unauthorized_users=[]` get you what you need?  (I.e., to be able to run EG as root?)

The properties are based on traitlets and, I agree, traitlets can be a bit finicky, especially when it comes to multi-valued options.

**Comment by Litchilitchy** [comment]
@kevin-bates yes, `...unauthorized_users={}` would raise error and `...unauthorized_users=[]` gets what I need.

The `...unauthorized_users={}` is the default style and maybe we could ask @ridwanoabdulazeez how he fix it. `...unauthorized_users=[]` is just the way I do.
